permalink: /:categories/:year/:month/:day/:title 

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
markdown: rdiscount
pygments: true

title : imYelo
author :
  name : yelo
  email : zhihuzeye@gmail.com
  github : imyelo

iytheme :
  ASSET_PATH: /asset

  disqus :
    short_name : imyelo 